name: release
on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Git
        run: |
          git config user.name ${{ secrets.USER_NAME }}
          git config user.email ${{ secrets.USER_EMAIL }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn version ${{ github.event.inputs.bump_type }}
      - name: Push tag to GitHub
        run: |
          git push
          git push --tags
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release to GitHub
        run: gh release create "v$(jq -r '.version' package.json)" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
